os:
  - linux
  - osx
env:
  - DISPLAY=:99.0
  - NODE_VERSION="0.12"
before_install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
install:
  - npm install
  - npm install mocha
before_script:
  - "sh -e /etc/init.d/xvfb start"
script:
  - node test/selenium-init.js
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo $(which node) test/selenium-chrome-init.js; fi
  - npm test
sudo: required
