language: node_js
os:
  - linux
  - osx
node_js:
  - "0.12"
env:
  - DISPLAY=:99.0
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - npm install mocha
script:
  - node test/selenium-init.js
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo $(which node) test/selenium-chrome-init.js; fi
  - npm test
sudo: required
cache:
  directories:
    - node_modules
